### ISSUE TITLE
Failed to reload the block-comment-lines package stylesheets

### ISSUE THREAD

**Issue by radarsu** [kaasbaardje/block-comment-lines#1]
[Enter steps to reproduce below:]
1. Changed Theme.
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [block-comment-lines](https://github.com/kaasbaardje/block-comment-lines) package, v0.2.4
### Stack Trace

Failed to reload the block-comment-lines package stylesheets

```
At EMFILE: too many open files, open 'C:\Users\Artur\.atom\packages\block-comment-lines\styles\block-comment-lines.less'

Error: EMFILE: too many open files, open 'C:\Users\Artur\.atom\packages\block-comment-lines\styles\block-comment-lines.less'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:307:21)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:286:21)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:501:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:500:59)
  at Package.module.exports.Package.reloadStylesheets (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:736:14)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\atom.js:867:22
  at Emitter.module.exports.Emitter.emit (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:375:27
  at _fulfilled (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\q\q.js:564:44
  at flush (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\q\q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
  3x -2:17.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:17 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:17 editor:newline (atom-text-editor.editor.is-focused)
     -2:15.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:13.2.0 core:undo (atom-text-editor.editor.is-focused)
     -2:10.1.0 core:cut (atom-text-editor.editor.is-focused)
     -2:09.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:07.9.0 clipboard-history:copy (atom-text-editor.editor.is-focused)
     -2:06.1.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:55.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:41.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:38.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:20.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:05.6.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "file-icons",
      "slack-chat"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.12
atom-html-preview, v0.1.11
auto-id-class, v0.2.6
autocomplete-modules, v1.1.0
block-comment-lines, v0.2.4
cdnjs, v1.5.0
clipboard-history, v0.6.6
color-picker, v2.0.12
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
docblockr, v0.7.3
docs-snippets, v0.8.0
font-viewer, v0.3.0
fonts, v0.6.0
foundation5-snippets, v0.2.2
htmlhint, v1.1.3
js-patterns-atom-snippets, v0.2.1
jshint, v1.8.0
keyboard-localization, v1.4.8
keycodes, v0.1.4
local-server-express, v0.3.1
minimap, v4.13.3
pigments, v0.15.0
Remote-FTP, v0.7.2
seti-icons, v0.4.5
smart-tags, v0.1.0
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by MoonByteShaker** [comment]
Thanks for reporting :-)
Since i can reproduce your reported bug even when my package is uninstalled or just disabled, i think the origin of this bug lies somewhere deeper in the atom editor. It would be nice if you can check this too. 
Seems to be a strange bug for me...
