### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bufferRangeForScopeAtCursor' of undefined

### ISSUE THREAD

**Issue by betapcode** [kaasbaardje/block-comment-lines#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [block-comment-lines](https://github.com/kaasbaardje/block-comment-lines) package, v0.2.4
### Stack Trace

Uncaught TypeError: Cannot read property 'bufferRangeForScopeAtCursor' of undefined

```
At /Users/betapcode/.atom/packages/block-comment-lines/lib/block-comment-lines.coffee:61

TypeError: Cannot read property 'bufferRangeForScopeAtCursor' of undefined
    at Object.module.exports.methods.isCursorInBlockComment (/Users/betapcode/.atom/packages/block-comment-lines/lib/block-comment-lines.coffee:61:28)
    at Object.module.exports.methods.removeBracket (/Users/betapcode/.atom/packages/block-comment-lines/lib/block-comment-lines.coffee:132:17)
    at atom-workspace.module.exports.toggle (/Users/betapcode/.atom/packages/block-comment-lines/lib/block-comment-lines.coffee:7:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -6:52.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:23.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:22.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:18.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:17.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:23.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:23.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:43.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:42.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:27 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:55.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.3.0 window:install-shell-commands (atom-text-editor.editor.mini.is-focused)
     -0:10.7.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 block-comment-lines:toggle (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-autocomplete-php, v0.18.7
atom-ternjs, v0.12.2
autocomplete-ionic-framework, v0.2.2
autocomplete-php, v0.3.7
autocomplete-python, v1.4.4
block-comment-lines, v0.2.4
csslint, v1.1.4
emmet, v2.3.18
highlight-line, v0.11.0
highlight-selected, v0.11.1
jsformat, v0.9.0
jslint, v1.5.1
language-javascript-better, v1.7.1
linter, v1.11.3
linter-csslint, v1.2.0
node-debugger, v1.3.2
nodejs-snippets, v2.0.0
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.2
php-debug, v0.1.4
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by facuescobar** [comment]
This issue occurs when the user press Alt+Shift+B on Settings Tab
